# -*- coding: utf-8 -*-
"""Apriori - Optimized

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lXb0AcKEV9Yh5bFkzba0zpmVcygRffAq

# Import Data
"""
import apriori_functions
import pandas as pd

if __name__ == '__main__':
    print("phase1")
    dataSet = pd.read_csv('Data\data1.2.csv')
    print("phase2")
    dataSet.head(100)
    print("phase3")

    """# Data Preprocessing"""

    apriori_functions.preProcessing(dataSet)

    C1 = apriori_functions.createC1(dataSet.to_numpy())
    D = list(map(set, dataSet.to_numpy()))
    L1, suppDat0 = apriori_functions.scanD(D, C1, 0.5)

    print("phase4")
    print("C1 -  ", C1, " D - ", D, " L1 - ", L1)

    freqItems, suppData = apriori_functions.apriori(dataSet.to_numpy(), minSupport=0.5)

    rules = apriori_functions.generateRules(freqItems, suppData, minConf=0.7)
    print("jhgujhg")
    print(rules)

    final_Rules = pd.DataFrame(rules,
                               columns=['ItemA', 'ItemB', 'ConfidanceA->B', 'ConfidanceB->A', 'Support(A,B)',
                                        'Support(A)',
                                        'Support(B)', 'Lift'])
    print(final_Rules)

"""Fuzzy Association Rules

---



IF (Temperature is Strong Fever) AND (Skin is Yellowish)
AND (Loss of appetite is Profound) → (Hepatitis is Acute)

The rule states that if a person has a Strong Fever, Yellowish
skin and Profound Loss of appetite, then the person has Acute
Hepatitis
"""
