DATA_FILE_PATH = 'Data/data_final_1_5.csv'
FREQ_ITEMS_FILE_PATH = 'output/freqItems.csv'
FREQ_ITEM_FORMATTED_FILE_PATH = '/output/freqItems_formatted.csv'
SUPP_DATA_FILE_PATH = 'output/suppData'
FINAL_RULES_FILE_PATH = 'output/output_1_11.csv'
TRAIN_ENCODED = 'output/train_encoded.csv'

C1_FILE_PATH = 'output/c1.npy'
L1_FILE_PATH = 'output/L1.npy'
D_FILE_PATH = 'output/D.npy'
SUPP_0_PATH = 'output/supp0.npy'

# Columns of final rules dataset

# ITEM_A = 'ItemA'
# ITEM_B = 'ItemB'
ITEM_A = 'antecedents'
ITEM_B = 'consequents'
CONFIDENCE_AB = 'ConfidenceA->B'
CONFIDENCE_BA = 'ConfidenceB->A'
SUPPORT_AB = 'Support(A,B)'
SUPPORT_A = 'Support(A)'
SUPPORT_B = 'Support(B)'
LIFT = 'Lift'

# One hot encode feature list

P_TCP = 'p-TCP'
P_HTTP = 'p-HTTP'
P_SSH = 'p-SSH'
P_DNS = 'p-DNS'
P_ARP = 'p-ARP'
P_SSHV2 = 'p-SSHv2'
L_0 = 'l-0.0'
L_1 = 'l-1.0'
L_2 = 'l-2.0'
D_80 = 'd-80'
D_42972 = 'd-42972'
D_34230 = 'd-34230'
D_50822 = 'd-50822'
D_53 = 'd-53'
D_22 = 'd-22'
D_56040 = 'd-56040'
D_161 = 'd-161'
D_443 = 'd-443'
R_PUBLIC = 'r-PUBLIC'
R_PRIVATE = 'r-PRIVATE'
R_NON = 'r-NON'
X_IN = 'x-IN'
X_OUT = 'x-OUT'
X_NON = 'x-NON'
C_A1 = 'c-A1'
C_A2 = 'c-A2'
C_A3 = 'c-A3'

CIDR = ["11.0.0.0/24"]
